export const SEQUELIZE_PROVIDER='SEQUELIZE';
export const USERS_REPOSITORY='USERS_REPOSITORY';
export const ROLES_REPOSITORY='ROLES_REPOSITORY';
export const USER_ROLES_REPOSITORY='USER_ROLES_REPOSITORY';
export const POSTS_REPOSITORY='POSTS_REPOSITORY';
export const PROMTS_REPOSITORY='PROMTS_REPOSITORY';
export const GENERATED_RESPONSE_REPOSITORY='GENERATED_RESPONSE_REPOSITORY';